### PR TITLE
let user decide when to reset input value

### LINKED ISSUE #2: Clicking outside the text input twice sets the element's value to ''
This can be replicated with the demo.  Select an option and click outside the text input twice.

I think this is happening because of some of the logic between Autocomplete's `hide` method and Complement's `_onblur` method.

### PR DESCRIPTION
**Pull request by kvnneff**
fixes https://github.com/jonathanong/autocomplete/issues/2

### CODE REVIEW

**Comment by jonathanong** [comment]
go for it :D

**Comment by jonathanong** [comment]
can you add a changelog?

**Comment by kvnneff** [comment]
:) how's that look?

**Comment by jonathanong** [comment]
i only expected it for your change. :+1:

**Comment by kvnneff** [comment]
I _think_ you're waiting on me to merge this?  But it doesn't seem that I have write access :)

**Comment by jonathanong** [comment]
oh duh

**Comment by jonathanong** [comment]
i assumed you were already a collab. haha. added!

**Pull request merged**
